# Generated by Django 5.1 on 2024-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
